import { getScoreEmoji } from '../scoring.js';

export function generateMarkdownReport({ score, counts, findings, scanDuration, targetPath }) {
  const grade = getScoreEmoji(score);
  const date = new Date().toISOString().split('T')[0];
  const totalIssues = findings.length;

  let md = '';

  // Header
  md += `# Shipwryte Security Report\n\n`;
  md += `**Date:** ${date}  \n`;
  md += `**Target:** \`${targetPath}\`  \n`;
  md += `**Scan Duration:** ${scanDuration}s  \n\n`;

  // Score
  md += `## Security Score: ${score}/100 (${grade})\n\n`;

  if (totalIssues === 0) {
    md += `No issues found. Your code looks clean!\n\n`;
  } else {
    md += `| Severity | Count |\n`;
    md += `|----------|-------|\n`;
    if (counts.critical > 0) md += `| Critical | ${counts.critical} |\n`;
    if (counts.high > 0) md += `| High | ${counts.high} |\n`;
    if (counts.medium > 0) md += `| Medium | ${counts.medium} |\n`;
    if (counts.low > 0) md += `| Low | ${counts.low} |\n`;
    md += `| **Total** | **${totalIssues}** |\n\n`;
  }

  // Findings by severity
  const severityOrder = ['critical', 'high', 'medium', 'low'];
  const severityLabels = {
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  };
  const severityIcons = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
  };

  for (const sev of severityOrder) {
    const sevFindings = findings.filter(f => f.severity === sev);
    if (sevFindings.length === 0) continue;

    md += `## ${severityIcons[sev]} ${severityLabels[sev]} Issues (${sevFindings.length})\n\n`;

    for (const f of sevFindings) {
      md += `### ${f.title}\n\n`;
      md += `${f.description}\n\n`;
      if (f.file) {
        md += `**Location:** \`${f.file}\``;
        if (f.line) md += ` (line ${f.line})`;
        md += `\n\n`;
      }
      md += `**Recommendation:** ${f.recommendation}\n\n`;
      md += `---\n\n`;
    }
  }

  // CTA
  md += `## What This Scan Covers\n\n`;
  md += `This automated scan checks for:\n`;
  md += `- Hardcoded secrets and API keys\n`;
  md += `- Known dependency vulnerabilities (CVEs)\n`;
  md += `- Common code security patterns (OWASP Top 10)\n`;
  md += `- Configuration issues\n\n`;

  md += `## What It Doesn't Cover\n\n`;
  md += `Automated scans catch surface-level issues, but they can't check:\n`;
  md += `- Is your authentication logic actually sound?\n`;
  md += `- What happens in edge cases?\n`;
  md += `- What's your threat model?\n`;
  md += `- Are there business logic vulnerabilities?\n`;
  md += `- What's your attack surface?\n\n`;

  md += `**That's where humans come in.**\n\n`;

  md += `---\n\n`;
  md += `### Ready for a deeper review?\n\n`;
  md += `> This scan caught ${totalIssues} surface-level issue${totalIssues !== 1 ? 's' : ''}. `;
  md += `For a comprehensive security audit including auth review, threat modeling, and business logic analysis:\n>\n`;
  md += `> **[Book a Human Audit →](https://shipwryte.com/audit)**\n\n`;

  md += `---\n\n`;
  md += `*Generated by [Shipwryte Scan](https://shipwryte.com) — Free security scanning for AI-generated code.*\n`;

  return md;
}
